pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'admin-flow', url: 'https://github.com/AhamedMinhaj456/Motorbike_Service_Station_Reservation_System'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    def dockerImage = docker.build('admin-flow-frontend', "-f frontend/Dockerfile .")
                    dockerImage.push()
                }
            }
        }
        
        stage('Run Container') {
            steps {
                script {
                    docker.image('admin-flow-frontend').withRun('-p 8080:80') {
                    }
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh "kubectl apply -f path/to/deployment.yml"
                }
            }
        }
    }
    
    post {
        always {
            script {
                docker.image('admin-flow-frontend').stop()
                docker.image('admin-flow-frontend').remove()
            }
        }
    }
}
