pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from the repository
                git branch: 'admin-flow', url: 'https://github.com/AhamedMinhaj456/Motorbike_Service_Station_Reservation_System'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                  def dockerImage = docker.build('admin-flow/frontend-app', '--file path/to/Dockerfile .')
                  dockerImage.push()
                }

            }
        }
        
        stage('Run Container') {
            steps {
                script {
                    docker.image('admin-flow/frontend-app').run('-p 8080:80')
                }
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                kubernetesDeploy(
                    kubeconfigId: 'my-kube-config', 
                    configs: 'path/to/deployment.yml', 
                    enableConfigSubstitution: true
                )
            }
        }
    }
    
    post {
        always {
            script {
                docker.image('admin-flow/frontend-app').stop()
                docker.image('admin-flow/frontend-app').remove()
            }
        }
    }
}
