apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-flow-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: admin-flow
  template:
    metadata:
      labels:
        app: admin-flow
    spec:
      containers:
        - name: admin-flow-container
          image: your-docker-registry/admin-flow-frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              value: "database-server"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
